### ISSUE TITLE
Update the branch policies for the `main` branch

### ISSUE THREAD

**Issue by toddysm** [notaryproject/.github#2]
To enhance the security for the governance repo, I would like to propose to Use the following rules for `main` branch:
Note: @SteveLasker changed the list to be checkboxes, to indicate which are complete:
- [x] Require PR before merging
- [x] Require 3 approvals
- [x] Dismiss stale PR approvals when new commits are pushed
- [x] Require review from Code Owners
- [x] Require status checks to pass before merging
- [ ] Require conversation resolution before merging
- [x] Require signed commits
- [x] Do not allow bypass the above settings

**Comment by yizha1** [comment]
LGTM but IANAM

**Comment by iamsamirzon** [comment]
LGTM but IANAM

**Comment by SteveLasker** [comment]
I've added all but require conversation resolution as this one feels ominous and a means to filibuster. 
Maintainers should have the flexibility to redirect to a new issue and accept or not accept PR feedback. 

I've left this issue open for discussion if folks feel otherwise, or we can try this out, and see how it works in practice.

**Comment by vaninrao10** [comment]
LGTM but IANAM

**Comment by iamsamirzon** [comment]
LGTM but IANAM

**Comment by priteshbandi** [comment]
LGTM but IANAM

**Comment by toddysm** [comment]
This change is complete.
