### ISSUE TITLE
patrickzheng@microsoft.com github account relink

### ISSUE THREAD

**Issue by Two-Hearts** [notaryproject/.github#27]
Last week, I lost access to my github account [patrickzheng200](https://github.com/patrickzheng200):
Since I'm in Shanghai, I'm not able to receive any 2fa SMS from Github as they removed (China +86) from their country code. And due to technical issues on my PC, I couldn't retrieve the recovery codes before I had to reinstall the machine's OS.
We sent two tickets and three emails to Github support but they couldn't provide any help on it.

As discussed in the community meeting, I unlinked my primary email `patrickzheng@microsoft.com` and relinked it to my new Github account [Two-Hearts](https://github.com/Two-Hearts). All my commit histories have been transferred to the new Github account.
As suggested by @yizha1, we think the next step would be removing `patrickzheng200` and adding `Two-Hearts` to maintainers of [notation](https://github.com/notaryproject/notation), [notation-go](https://github.com/notaryproject/notation-go), and [notation-core-go](https://github.com/notaryproject/notation-core-go). Thanks.

**Comment by FeynmanZhou** [comment]
LGTM to switch to a new account and add @Two-Hearts to become maintainer [notation](https://github.com/notaryproject/notation), [notation-go](https://github.com/notaryproject/notation-go), and [notation-core-go](https://github.com/notaryproject/notation-core-go).

**Comment by yizha1** [comment]
Hello Notary maintainers, 
@priteshbandi @vaninrao10@iamsamirzon @rgnote @gokarnm @shizhMSFT @JeyJeyGao @toddysm @FeynmanZhou @SteveLasker @justincormack @NiazFK 

Please be aware of the changes as @Two-Hearts described.

Since `patrickzheng200` was the maintainers for [notation](https://github.com/notaryproject/notation), [notation-go](https://github.com/notaryproject/notation-go), and [notation-core-go](https://github.com/notaryproject/notation-core-go), so we need to 
- remove `patrickzheng200` from MAITAINERS and CODEOWNERS file under the three subprojects [notation](https://github.com/notaryproject/notation), [notation-go](https://github.com/notaryproject/notation-go), and [notation-core-go](https://github.com/notaryproject/notation-core-go).
- remove `patrickzheng200` from GitHub teams `notaryproject-notation-core-go-maintainers`, `notaryproject-notation-go-maintainers`, `notaryproject-notation-maintainers`
- add @Two-Hearts to MAITAINERS and CODEOWNERS file under [notation](https://github.com/notaryproject/notation), [notation-go](https://github.com/notaryproject/notation-go), and [notation-core-go](https://github.com/notaryproject/notation-core-go).
- add @Two-Hearts to GitHub teams `notaryproject-notation-core-go-maintainers`, `notaryproject-notation-go-maintainers`, `notaryproject-notation-maintainers`

Please comment if you LGTM. Feel free add anything else that needs to be taken care of.

**Comment by lata-11** [comment]
Hey @yizha1 ! I would like take it. Please assign this to me.

**Comment by JeyJeyGao** [comment]
LGTM to switch to a new account and add @Two-Hearts to become maintainer [notation](https://github.com/notaryproject/notation), [notation-go](https://github.com/notaryproject/notation-go), and [notation-core-go](https://github.com/notaryproject/notation-core-go).

**Comment by shizhMSFT** [comment]
LGTM

**Comment by toddysm** [comment]
LGTM. When the PR for the CODEOWNERS and MAINTAINERS files is approved, I will update the teams with the new GH handle. @yizha1, can we please link the PRs for those updates to this issue?

**Comment by priteshbandi** [comment]
LGTM

**Comment by vaninrao10** [comment]
LGTM

**Comment by yizha1** [comment]
Thank you all. 

We now have `5` approvals out of the `9` maintainers under governance `.github` repo, and `3` approvals out of `5` (excluding patrickzheng200 as the issue owner) subproject `notation`/`notation-go`/`notation-core-go` maintainers.

So, I will proceed to create PRs to add @Two-Hearts as maintainers according to previous comment https://github.com/notaryproject/.github/issues/27#issuecomment-1548942718

PRs will be linked here later once they are created.

**Comment by yizha1** [comment]
> LGTM. When the PR for the CODEOWNERS and MAINTAINERS files is approved, I will update the teams with the new GH handle. @yizha1, can we please link the PRs for those updates to this issue?

@toddysm PRs were created (under reviewing at this moment). Note it seems there are errors, for example:

`Unknown owner on line 3: make sure @Two-Hearts exists and has write access to the repository`

- https://github.com/notaryproject/notation/pull/672
- https://github.com/notaryproject/notation-go/pull/310
- https://github.com/notaryproject/notation-core-go/pull/145

**Comment by yizha1** [comment]
@toddysm PRs for fixing account issues for subprojects `notation`, `notation-go` and `notation-core-go` were merged. Please help to update GitHub Teams

**Comment by toddysm** [comment]
GH Teams are updated:
- Old handle for @patrickzheng200 is removed
- Invites to @Two-Hearts are sent for all three repos above

**Comment by yizha1** [comment]
Thank you all. The account issue was fixed.
